import type { AgentDrawDocument } from "./model/schema";

export const seedDocument: AgentDrawDocument = {
  format: "agent-draw",
  version: "0.1",
  id: "agent-draw-system-map",
  title: "Agent Draw · system map",
  revision: 0,
  plugins: { "agent-draw.core": "^0.1.0", "agent-draw.api": "^0.1.0" },
  nodes: [
    {
      id: "endpoint-list-projects",
      type: "agent-draw.api/endpoint",
      label: "List projects",
      position: { x: 80, y: 110 },
      size: { w: 260, h: 116 },
      ports: [
        { id: "request", direction: "input", label: "request" },
        { id: "invokes", direction: "output", label: "invokes" },
      ],
      data: {
        method: "GET",
        url: "https://httpbin.org/anything/projects",
        headers: { accept: "application/json" },
        description: "Returns the projects visible to the current agent.",
      },
      capabilityRefs: ["http-runtime"],
      extensions: {
        "agent-draw.provenance": {
          source: "examples/system-map.agent-draw.json",
        },
      },
    },
    {
      id: "service-api",
      type: "agent-draw.core/service",
      label: "Project API",
      position: { x: 445, y: 110 },
      size: { w: 240, h: 116 },
      ports: [
        { id: "request", direction: "input", label: "request" },
        { id: "calls", direction: "output", label: "calls" },
      ],
      data: { runtime: "Node.js", package: "server" },
      capabilityRefs: [],
      extensions: {},
    },
    {
      id: "database-projects",
      type: "agent-draw.core/database",
      label: "projects.db",
      position: { x: 805, y: 110 },
      size: { w: 236, h: 116 },
      ports: [
        { id: "query", direction: "input", label: "query" },
        { id: "schema", direction: "output", label: "schema" },
      ],
      data: { engine: "SQLite", tables: ["projects", "sources", "documents"] },
      capabilityRefs: [],
      extensions: {},
    },
    {
      id: "table-projects",
      type: "agent-draw.core/table",
      label: "projects",
      position: { x: 1140, y: 25 },
      size: { w: 270, h: 180 },
      ports: [
        { id: "database", direction: "input", label: "database" },
        { id: "query", direction: "input", label: "query" },
        { id: "reference", direction: "input", label: "reference" },
        { id: "references", direction: "output", label: "references" },
      ],
      data: {
        columns: [
          { name: "id", type: "uuid", primaryKey: true },
          { name: "name", type: "text" },
          { name: "created_at", type: "datetime" },
        ],
      },
      capabilityRefs: [],
      extensions: {},
    },
    {
      id: "table-sources",
      type: "agent-draw.core/table",
      label: "sources",
      position: { x: 1140, y: 245 },
      size: { w: 270, h: 180 },
      ports: [
        { id: "database", direction: "input", label: "database" },
        { id: "query", direction: "input", label: "query" },
        { id: "reference", direction: "input", label: "reference" },
        { id: "references", direction: "output", label: "references" },
      ],
      data: {
        columns: [
          { name: "id", type: "uuid", primaryKey: true },
          { name: "project_id", type: "uuid", foreignKey: true },
          { name: "uri", type: "text" },
        ],
      },
      capabilityRefs: [],
      extensions: {},
    },
    {
      id: "table-documents",
      type: "agent-draw.core/table",
      label: "documents",
      position: { x: 1140, y: 465 },
      size: { w: 270, h: 180 },
      ports: [
        { id: "database", direction: "input", label: "database" },
        { id: "query", direction: "input", label: "query" },
        { id: "reference", direction: "input", label: "reference" },
        { id: "references", direction: "output", label: "references" },
      ],
      data: {
        columns: [
          { name: "id", type: "uuid", primaryKey: true },
          { name: "source_id", type: "uuid", foreignKey: true },
          { name: "content", type: "text" },
        ],
      },
      capabilityRefs: [],
      extensions: {},
    },
    {
      id: "file-router",
      type: "agent-draw.core/file",
      label: "server/routes/projects.ts",
      position: { x: 425, y: 355 },
      size: { w: 310, h: 104 },
      ports: [{ id: "exports", direction: "output", label: "exports" }],
      data: { path: "server/routes/projects.ts" },
      capabilityRefs: [],
      extensions: {},
    },
    {
      id: "external-github",
      type: "agent-draw.core/external",
      label: "GitHub connector",
      position: { x: 805, y: 355 },
      size: { w: 236, h: 104 },
      ports: [{ id: "request", direction: "input", label: "request" }],
      data: { connector: "github", status: "planned" },
      capabilityRefs: [],
      extensions: {},
    },
  ],
  edges: [
    {
      id: "edge-route-service",
      type: "agent-draw.api/invokes",
      label: "invokes",
      source: { nodeId: "endpoint-list-projects", portId: "invokes" },
      target: { nodeId: "service-api", portId: "request" },
      data: {},
      extensions: {},
    },
    {
      id: "edge-service-db",
      type: "agent-draw.core/reads",
      label: "reads",
      source: { nodeId: "service-api", portId: "calls" },
      target: { nodeId: "table-projects", portId: "query" },
      data: {},
      extensions: {},
    },
    {
      id: "edge-db-projects",
      type: "agent-draw.core/contains",
      label: "contains",
      source: { nodeId: "database-projects", portId: "schema" },
      target: { nodeId: "table-projects", portId: "database" },
      data: {},
      extensions: {},
    },
    {
      id: "edge-db-sources",
      type: "agent-draw.core/contains",
      label: "contains",
      source: { nodeId: "database-projects", portId: "schema" },
      target: { nodeId: "table-sources", portId: "database" },
      data: {},
      extensions: {},
    },
    {
      id: "edge-db-documents",
      type: "agent-draw.core/contains",
      label: "contains",
      source: { nodeId: "database-projects", portId: "schema" },
      target: { nodeId: "table-documents", portId: "database" },
      data: {},
      extensions: {},
    },
    {
      id: "edge-sources-projects",
      type: "agent-draw.core/references",
      label: "project_id",
      source: { nodeId: "table-sources", portId: "references" },
      target: { nodeId: "table-projects", portId: "reference" },
      data: {},
      extensions: {},
    },
    {
      id: "edge-documents-sources",
      type: "agent-draw.core/references",
      label: "source_id",
      source: { nodeId: "table-documents", portId: "references" },
      target: { nodeId: "table-sources", portId: "reference" },
      data: {},
      extensions: {},
    },
    {
      id: "edge-file-service",
      type: "agent-draw.core/depends-on",
      label: "implements",
      source: { nodeId: "file-router", portId: "exports" },
      target: { nodeId: "service-api", portId: "request" },
      data: {},
      extensions: {},
    },
    {
      id: "edge-service-github",
      type: "agent-draw.core/calls",
      label: "syncs",
      source: { nodeId: "service-api", portId: "calls" },
      target: { nodeId: "external-github", portId: "request" },
      data: {},
      extensions: {},
    },
  ],
  views: [{ id: "architecture", name: "Architecture", extensions: {} }],
  capabilities: [
    {
      id: "http-runtime",
      kind: "network.http",
      config: { policy: "public-network-only" },
    },
  ],
  metadata: { createdBy: "agent-draw", purpose: "MVP demo" },
  extensions: {},
};
